### ISSUE TITLE
The TO-DO list

### ISSUE THREAD

**Issue by adriantodt** [OpenMultiplicity/generator#1]
- [ ] Refactor the generator's original code
- [ ] Post and article licensing
- [ ] Meta tags for author/description/keywords
- [ ] Twitter/Facebook cards support
- [ ] Head Image support
